export const bookNames: Record<string, string> = {
    gn: "Genesis",
    ex: "Exodus",
    lv: "Leviticus",
    nm: "Numbers",
    dt: "Deuteronomy",
    js: "Joshua",
    jd: "Judges",
    rt: "Ruth",
    "1s": "1 Samuel",
    "2s": "2 Samuel",
    "1k": "1 Kings",
    "2k": "2 Kings",
    "1ch": "1 Chronicles",
    "2ch": "2 Chronicles",
    ez: "Ezra",
    ne: "Nehemiah",
    es: "Esther",
    jb: "Job",
    ps: "Psalms",
    pr: "Proverbs",
    ec: "Ecclesiastes",
    sn: "Song of Solomon",
    is: "Isaiah",
    jr: "Jeremiah",
    lm: "Lamentations",
    ezk: "Ezekiel",
    dn: "Daniel",
    ho: "Hosea",
    jl: "Joel",
    am: "Amos",
    ob: "Obadiah",
    jn: "Jonah",
    mi: "Micah",
    na: "Nahum",
    hk: "Habakkuk",
    zp: "Zephaniah",
    hg: "Haggai",
    zc: "Zechariah",
    ml: "Malachi",
    mt: "Matthew",
    mk: "Mark",
    lk: "Luke",
    jh: "John",
    ac: "Acts",
    rm: "Romans",
    "1co": "1 Corinthians",
    "2co": "2 Corinthians",
    gl: "Galatians",
    ep: "Ephesians",
    ph: "Philippians",
    cl: "Colossians",
    "1th": "1 Thessalonians",
    "2th": "2 Thessalonians",
    "1ti": "1 Timothy",
    "2ti": "2 Timothy",
    tt: "Titus",
    phm: "Philemon",
    hb: "Hebrews",
    jm: "James",
    "1pe": "1 Peter",
    "2pe": "2 Peter",
    "1jn": "1 John",
    "2jn": "2 John",
    "3jn": "3 John",
    jd_ep: "Jude", // 'jd' is Judges, usually Jude is 'ju' or similar, checking collision
    re: "Revelation"
};

// Helper to handle potential variations if needed
export const getBookName = (abbrev: string): string => {
    return bookNames[abbrev.toLowerCase()] || abbrev;
};
